name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (you can change the timing)

  workflow_dispatch: # Allows you to run this manually

jobs:
  build:
    name: Snake Animation
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Khatwangadhareddy
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v2
        with:
          name: snake-artifact
          path: dist
      - name: Push Snake Animation to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
